- hosts: php
  become: yes
  become_user: root
  tasks:
  - name: Install Ondrej PPA
    apt_repository:
      repo: ppa:ondrej/php
  - name: Update apt
    apt: cache_valid_time=86400 update_cache=yes upgrade=yes
  - name: Install PHP packages
    apt: name="{{item}}" state=latest
    loop:
      - php7.4-bcmath
      - php7.4-bz2
      - php7.4-curl
      - php7.4-dba
      - php7.4-fpm
      - php7.4-gd
      - php7.4-gmp
      - php7.4-imap
      - php7.4-intl
      - php7.4-json
      - php7.4-ldap
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-odbc
      - php7.4-opcache
      - php7.4-pgsql
      - php7.4-readline
      - php7.4-snmp
      - php7.4-soap
      - php7.4-sqlite3
      - php7.4-tidy
      - php7.4-xml
      - php7.4-xmlrpc
      - php7.4-xsl
      - php7.4-zip
