- hosts: all
  strategy: free
  become: yes
  become_user: root
  tasks:
  - name: Update apt
    apt: cache_valid_time=86400 update_cache=yes upgrade=yes
  - name: Install basic applications
    apt: name={{item}} state=latest
    loop:
      - curl
      - dstat
      - jq
      - most
      - mtr-tiny
      - python
      - sharutils
      - software-properties-common
      - sysstat
      - unzip
      - vim-nox
      - wget
      - sysstat
